language: android

android:
  components:
  # Uncomment the lines below if you want to
  # use the latest revision of Android SDK Tools
  - tools
  - platform-tools

  # The BuildTools version used by your project
  - build-tools-28.0.0

  # The SDK version used to compile your project
  - android-28

  # Additional components
  - extra-google-google_play_services
  - extra-google-m2repository
  - extra-android-m2repository

  # Specify at least one system image,
  # if you need to run emulator(s) during your tests
  - sys-img-x86-android-26
  - sys-img-armeabi-v7a-android-17

  licenses:
  - 'android-sdk-preview-license-52d11cd2'
  - 'android-sdk-license-.+'
  - 'google-gdk-license-.+'

before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
  - $HOME/.android/build-cache

install:
- echo yes | ${ANDROID_HOME}/tools/bin/sdkmanager "build-tools;28.0.3"
script:
- ./gradlew check

jobs:
  include:
    - stage: check
      name: "Check Push"
      script: ./gradlew check
    - stage: test
      name: "Run Tests"
      script: ./gradlew test
    - stage: deploy
      name: "Deploy to Bintray"
      script: ./gradlew bintrayUpload


stages:
  - check
  - test
  - name: deploy
    if: branch = master
